# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

services:
  ingress:
    image: caddy:2.8-alpine
    environment:
      EXPOSE_INGRESS_DOMAIN: ${EXPOSE_INGRESS_DOMAIN}
      EXPOSE_INGRESS_TLS_PROVIDER: ${EXPOSE_INGRESS_TLS_PROVIDER}
    ports:
      - mode: host
        target: 80
        published: 80
      - mode: host
        target: 443
        published: 443
    networks:
      expose-network:
    configs:
      - source: ingress_config
        target: /etc/caddy/Caddyfile
    secrets:
      - source: ingress_cf_origin_server.crt
        target: /run/secrets/cf_origin_server.crt
      - source: ingress_cf_origin_server.key
        target: /run/secrets/cf_origin_server.key
  expose:
    image: socheatsok78/expose:main
    environment:
      EXPOSE_SERVER_DOMAIN: ${EXPOSE_SERVER_DOMAIN}
      EXPOSE_SERVER_PORT: ${EXPOSE_SERVER_PORT}
      EXPOSE_CONFIG_SERVER_ENDPOINT_URL: ${EXPOSE_CONFIG_SERVER_ENDPOINT_URL}
      EXPOSE_SERVER_ADMIN_USERNAME_FILE: /run/secrets/expose_server_admin_username
      EXPOSE_SERVER_ADMIN_PASSWORD_FILE: /run/secrets/expose_server_admin_password
    networks:
      expose-network:
    hostname: expose.internal
    volumes:
      - type: volume
        source: expose-data
        target: /root/.expose
    secrets:
      - expose_server_admin_username
      - expose_server_admin_password
volumes:
  expose-data:
networks:
  expose-network:
configs:
  ingress_config:
    file: ./Caddyfile
secrets:
  ingress_cf_origin_server.crt:
    file: ./certs/cf_origin_server.crt
  ingress_cf_origin_server.key:
    file: ./certs/cf_origin_server.key
  expose_server_admin_username:
    file: ./secrets/expose_server_admin_username
  expose_server_admin_password:
    file: ./secrets/expose_server_admin_password
