name: "Build"

on:
  push:
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - id: alpine
        uses: actions-matrix/alpine-matrix-action@v1
    outputs:
      matrix: ${{ steps.alpine.outputs.matrix }}

  build:
    needs: generate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix: ${{ fromJson(needs.generate.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        env:
          ALPINE_VERSION: ${{ matrix.version }}
        with:
          images: |
            docker.io/${{ github.actor }}/expose
            ghcr.io/${{ github.actor }}/expose
          flavor: latest=false
          tags: type=raw,value=${{ matrix.version }}

      - name: Generate GitHub metadata
        id: github-meta
        uses: dockerbakery/github-metadata-action@v2

      - name: Build and push
        uses: docker/bake-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          files: |
            ./docker-bake.hcl
            ${{ steps.docker-meta.outputs.bake-file }}
            ${{ steps.github-meta.outputs.bake-file }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Docker Metadata Summary
        uses: dockerbakery/docker-metadata-summary@v1
